# IMPORTANT: This is a TEMPLATE file!
# Replace this with your actual hardware-configuration.nix generated by:
#   sudo nixos-generate-config --show-hardware-config > hardware-configuration.nix
#
# Or copy your existing /etc/nixos/hardware-configuration.nix here

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # ============================================
  # BOOT - Modify based on your hardware
  # ============================================
  boot.initrd.availableKernelModules = [ 
    "nvme" 
    "xhci_pci" 
    "ahci" 
    "usb_storage" 
    "sd_mod" 
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ]; # or "kvm-amd" for AMD
  boot.extraModulePackages = [ ];

  # ============================================
  # FILESYSTEMS - MUST BE CUSTOMIZED
  # ============================================
  # Example for a typical setup with encrypted root
  # Uncomment and modify based on your disk layout
  
  # fileSystems."/" = {
  #   device = "/dev/disk/by-uuid/YOUR-ROOT-UUID";
  #   fsType = "ext4";
  #   # Or for btrfs:
  #   # fsType = "btrfs";
  #   # options = [ "subvol=@" "compress=zstd" "noatime" ];
  # };

  # fileSystems."/boot" = {
  #   device = "/dev/disk/by-uuid/YOUR-BOOT-UUID";
  #   fsType = "vfat";
  # };

  # fileSystems."/home" = {
  #   device = "/dev/disk/by-uuid/YOUR-HOME-UUID";
  #   fsType = "ext4";
  # };

  # swapDevices = [
  #   { device = "/dev/disk/by-uuid/YOUR-SWAP-UUID"; }
  # ];

  # ============================================
  # NETWORKING
  # ============================================
  # networking.useDHCP = lib.mkDefault true;

  # ============================================
  # HARDWARE
  # ============================================
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  
  # CPU microcode - uncomment the appropriate one
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Enable all firmware
  hardware.enableRedistributableFirmware = true;
}
